---
- hosts: default
  sudo: yes
  vars:
    gvm_install_script: 'get.gvmtool.net'

  tasks:
  - name: gvm | check current installation
    stat: path=/home/tank/.gvm
    register: gvm_dir
    ignore_errors: True

  - name: gvm | install
    shell: curl -s "{{ gvm_install_script }}" | bash
    when: not gvm_dir.stat.exists
    args:
      chdir: /home/tank

  - name: gvm | update
    shell: su -l -c "gvm selfupdate" tank

  - name: gvm | install | groovy
    shell: su -l -c "gvm i groovy" tank

  - name: gvm | install | gradle
    shell: su -l -c "gvm i gradle" tank

  - name: gvm | install | springboot
    shell: su -l -c "gvm i springboot" tank
