---
- hosts: default
  sudo: yes
  vars:
    prelude_install_script: 'get.gvmtool.net'

  tasks:
  - name: gvm | check current installation
    stat: path=/home/tank/.gvm
    register: gvm_dir
    ignore_errors: True

  - name: gvm | install | curl
    apt: name=curl state=latest
    
  - name: gvm | install
    shell: curl -s "{{ prelude_install_script }}" | bash
    when: not gvm_dir.stat.exists
    args:
      chdir: /home/tank
